#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -e pulsemixer & disown ;;
	3) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
esac

vol=$(pamixer --get-volume)

iconget() {
    if [[ $vol -ge 66 ]]; then
            icon=""
    elif [[ $vol -ge 33 ]]; then
            icon=""
    elif [[ $vol -ge 0 ]]; then
            icon=""
    else
            icon=""
    fi ;}

iconget

printpastatus() {
   [[ $(pamixer --get-mute) = "true" ]] && echo -n  && exit
   
   echo ${icon}${vol}% ;
}
printpastatus
