#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -e pulsemixer & disown ;;
	3) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
esac

vol=$(pamixer --get-volume)

iconget() {
    if [[ $vol -ge 80 ]]; then
            icon=""
    elif [[ $NUM -ge 75 ]]; then
            icon=""
    elif [[ $NUM -ge 50 ]]; then
        icon=""
    elif [[ $NUM -ge 15 ]]; then
            icon=""
    ee
            icon=""
    fi ;}

iconget

printpastatus() {
   [[ $(pamixer --get-mute) = "true" ]] && echo -n  && exit
   
   echo ${icon}${vol}% ;
}
printpastatus
